version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Removes all compiled artifacts
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates the code coverage report
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates the code coverage report in HTML format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --html --open

  cov-cobertura:
    desc: Generates the code coverage report in "cobertura" format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --all-features --cobertura --output-path ./target/coverage-cobertura.xml

  cov-json:
    desc: Generates the code coverage summary report in JSON format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --all-features --json --output-path ./target/coverage-json.json

  cov-json-summary:
    desc: Generates the code coverage summary report in JSON format
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --all-features --json --summary-only --output-path ./target/coverage-json-summary.json

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in a browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  doc-priv:
    desc: Generates documentation with private items
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation with private items and opens it in a browser
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items --open

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo fmt

  test:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable test

  run:
    desc: Runs the application
    cmds:
      - cmd: cargo +stable run -- ./target/coverage-json-summary.json

  run-data:
    desc: Runs the application
    cmds:
      - cmd: cargo +stable run -- ./data/coverage.json
