version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo build

  clean:
    desc: Removes all compiled artifacts
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy
    cmds:
      - cmd: cargo clippy --all-targets

  cov:
    desc: Generates the code coverage report
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates the code coverage report in HTML format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage --html --open

  cov-summary:
    desc: Generates the code coverage summary report in JSON format
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage --json --summary-only | jq

  cov-badge:
    desc: Generates the code coverage badge
    cmds:
      - cmd: cargo build
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage --json --summary-only | ./target/debug/coverio --collapse --tag cov-badge-coverio

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in a browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc-priv:
    desc: Generates documentation with private items
    cmds:
      - cmd: cargo doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation with private items and opens it in a browser
    cmds:
      - cmd: cargo doc --no-deps --document-private-items --open

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo fmt

  test:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo test
